### ISSUE TITLE
Can't get passwordForgot to work for auto-confirmed users

### ISSUE THREAD

**Issue by guilsa** [frsechet/cognito-user-pool#2]
I have the same issue posted [here](https://forums.aws.amazon.com/thread.jspa?threadID=234841). In Cognito user `john`'s status is enabled / confirmed, so I am assuming this isn't an issue with having to verify email (or phone). I'm confused as the passwordForgot method returns `Cannot reset password for the user as there is no registered/verified email or phone_number`.

```
const data = { 'username': 'john' };
    CognitoUserPoolWrapper.passwordForgot(data, (err, result) => {
      console.log(result);
      console.log(err);
    })
```
Should I be using `GetUserAttributeVerificationCode`? Would it valuable to add this to cognito-user-pool?

**Comment by frsechet** [comment]
Hi @guilsa,

This is by design on Cognito. If your user is registered but has not verified their email, it means that as far as Cognito is concerned, the email is not active, and the user can not log in (if they just registered - see below for a different scenario where it's a bit more subtle). Hence, it does not make sense to say they forgot their password as they don't really have a valid account yet, and instead you should send a new verification email to them.

Cognito-user-pool is a server-side wrapper on the cognito user pool client library. For your use case, you should use the `signupResend` method *or* you should auto-verify the email yourself with a pre-signup trigger.

However, there is one scenario where the user would be locked out of their account and have no other solution than contact the cognito admin:
Let's say they created and verified their account already, so they can login, but at some point they modify their email address. If they don't click on the validation link, then log out and forget their password (they switch computer for example), they will not be able to reset the password (since their new email is not verified and the old email is inactive) and they can also not login anymore (since they forgot their password).

The only programmatic way out of this situation (other than clicking on "verify user" in the cognito user pool admin dashboard) is to use the `CognitoIdentityServiceProvider.adminUpdateUserAttributes` method and manually the `email_verified` field. Note that you should really be careful about this as it introduces a security flaw, in that people can change emails without verifying them.

**Comment by guilsa** [comment]
Hi @frsechet, thank you for your response. We're still figuring out if Cognito is the auth stack to go with, so please don't feel like responding to this is urgent. I'm still grasping the gist of this, so bare with me here.

I am manually creating users on the Cognito website. In my case users will be added to Cognito following an offline approval process. Not sure if this process changes things (i.e. in this case accounts shouldn't have to be verified).

```
If your user is registered but has not verified their email
```
Answer: I thought my user was verified already. Is `verified` not the same as the enabled/confirmed status in the Cognito dashboard? Options available during create a user phase include sending an invitation via email/sms and marking email/sms as verified. I played with this combination but still get the `Cannot reset password for the user as there is no registered/verified email or phone_number` returned.

```
clicking on "verify user" in the cognito user pool admin dashboard
```
Answer: I can't find a Verify User button anywhere. 

```
For your use case, you should use the signupResend method or you should auto-verify the email yourself with a pre-signup trigger.
```
Answer: I've tried that, didn't write down the error and deleted the code, but it was something about this user is already verified.

My intuition says I may be stuck on a state and need to use the `CognitoIdentityServiceProvider.adminUpdateUserAttributes` given as an admin I created the account `john`, so the system may be waiting for this as a next step.

**Comment by frsechet** [comment]
If you created your user from the admin dashboard, the status should be something like `User Status	Enabled / FORCE_CHANGE_PASSWORD`. This means that upon next login the user must change their password no matter what.

Sorry about the "clicking verify user", you are right, there isn't any. There is a disable user button, but it is not in "enable user" mode in the beginning. So not much you can do there and you have to use the `adminUpdateUserAttributes` method (you have to send an object like so:
```
{
  "Name": "email_verified",
  "Value": true
}
```

`email_verified` is different from the user being enabled or not, or the status they are in (see above). Cognito is VERY confusing, I agree. It took me a very long time to get used to it as well. It's quite powerful though when you understand a bit better how it works...

**Comment by guilsa** [comment]
Hey @frsechet can't believe the level of support. Great stuff. We are researching other solutions but I've staged a spike using cognito-user-pool with login/logout and forgot pw WIP. If need be I'll be back. Best.

Guil
