### ISSUE TITLE
federated provider signup/signin

### ISSUE THREAD

**Issue by adampotocki** [frsechet/cognito-user-pool#5]
Hi Francois,

Any plans on adding this here?

Thanks for all the hard work!

**Comment by frsechet** [comment]
Hi Adam,
what precisely do you have in mind?

**Comment by adampotocki** [comment]
Google/Facebook/Github signup and signin...not sure how that works with Cognito yet :/ Here is what I will be working on doing: Frontend signin/signup with one or more provider, then have a lambda get credentails from provider and pass it through to Cognito, essentially auto signup the user, or if already exists then sign in and return Cognito tokens...these tokens will later be used by a Custom Authorizer/Cognito User Pool Authorizer...is this somehow possible?

**Comment by frsechet** [comment]
You have the basic workflow right. I heard that AWS is going to release something a little bit more/better integrated between cognito user pool and federated identities "soon". Not sure what to expect exactly (or when).

The main concern I have with adding this functionality is that it requires me to make some design choices, while I managed to stay away from that in the original package. Basically besides sharing the name cognito, federated identities and user pool are two different products, and I think the unification should be left to the user depending on their use case. I couldn't find a one-size-fits-all solution yet.

**Comment by adampotocki** [comment]
hmm, i see do you know if I can use another lib or similar wrapper to help with provider->cognito user pool?

**Comment by frsechet** [comment]
As a matter of fact AWS just released this: https://aws.amazon.com/fr/about-aws/whats-new/2017/08/amazon-cognito-launches-general-availability-of-a-built-in-customizable-user-experience-for-sign-in-oauth-2-0-support-and-federation-with-facebook-login-with-amazon-google-and-saml-providers-for-user-pools/

I haven't had time to have a look (it's only a few hours old and I only read this link) so I suggest you start there and see what you need. I don't have much time to dig in now but perhaps I will adapt my package in September at some point. There are some improvements I want to add anyway (support for Promises, among others).

Otherwise, the only way to do what you describe is really through manual matching of tokens between user pool and federated identities. It's a bit painful really but there is/was no other way. I'm very curious whether this new tool above is any good...

**Comment by adampotocki** [comment]
awesome i will check it out, thanks for all your help and hard work :)
