### ISSUE TITLE
Why is refreshToken is used?

### ISSUE THREAD

**Issue by sallar** [frsechet/cognito-user-pool#8]
Hi, 

Thank you for the nice library. One question though: Why are you using `refreshToken` for everything instead of `accessToken` and `idToken`? What is the pointing of receiving them if you're going to use the refreshToken for everything?

Thank you
Sallar.

**Comment by frsechet** [comment]
Hi there,

To be completely honest, I don't use this library anymore, and it is not under active development anymore. I have no working testing environment setup and i don't remember why it is the way it is... I'm quite sure I remember there was a reason, but I can not say what it was for sure.


Now if I have to bet on something without installing the project again, I would say it was probably because using accessToken and idToken did not work in some of the methods as this package basically aggregates methods from the cogito javascript (client-side) and AWS node.js (server-side) SDKs, which may not have the same parameters. So for the sake of coherence, I probably chose to use refreshToken everywhere, which always works.


If you want to have a look and try a PR I will review it!
Let me know :-)

**Comment by sallar** [comment]
thanks! I'm using it here: https://github.com/cxcloud/core-services/blob/master/src/auth/index.ts
I think I'll be able to make a PR to your project as well :) Cheers!

**Comment by frsechet** [comment]
hey @sallar, turns out you are absolutely right :-)
I am currently fixing this and will push an update today.

**Comment by sallar** [comment]
@frsechet Thanks! Looking forward to using the new version :)

**Comment by frsechet** [comment]
It is published: npm install cognito-user-pool@^0.2.0
Enjoy!
